arm_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
    state_publish_rate: 100
    action_monitor_rate: 100

hand_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
        - panda_finger_joint1
        - panda_finger_joint2
    state_publish_rate: 100
    action_monitor_rate: 100


joint_state_controller:
  ros__parameters:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  

